#pragma once

#define _DARKEN_DEBUG 0

#define _DARKEN_DEBUG_INFO(MESSAGE)
#define _DARKEN_DEBUG_ERROR(MESSAGE)
#define _DARKEN_DEBUG_NOTICE(MESSAGE)
#define _DARKEN_DEBUG_WARNING(MESSAGE)

#include "implement/SGDK.h"